<#
.SYNOPSIS
    Installs the Zed remote-open listener as a hidden, self-healing Scheduled Task.

.DESCRIPTION
    Copies the listener into a stable local directory (a Scheduled Task cannot rely
    on reaching a \\wsl$ or network path), resolves the Zed CLI now so the task does
    not depend on runtime PATH, and registers the task behind a .vbs wrapper that
    runs it with no console window.

    Re-running is idempotent: the previous instance is stopped and the task is
    re-registered in place.

.EXAMPLE
    .\install-zed-listener.ps1

.EXAMPLE
    .\install-zed-listener.ps1 -ZedExe 'C:\Tools\Zed\bin\Zed.exe'

.EXAMPLE
    .\install-zed-listener.ps1 -Uninstall
#>
[CmdletBinding()]
param(
    [ValidateRange(1, 65535)]
    [int]$Port = 7682,

    [string]$ZedExe,

    [string]$InstallDir = (Join-Path $env:LOCALAPPDATA 'zed-listener'),

    [string]$TaskName = 'zed-open-listener',

    [switch]$Uninstall,

    [switch]$NoStart
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'ZedCli.ps1')

$ListenerName = 'zed-open-listener.ps1'
# Matches the wscript, cmd and pwsh layers in one pass: the .vbs and .ps1 file
# names share this stem, so matching the stem catches all three.
$ProcessMatch = 'zed-open-listener'
$VbsPath = Join-Path $InstallDir 'zed-open-listener-hidden.vbs'
$ScriptPath = Join-Path $InstallDir $ListenerName
$LogFile = Join-Path $InstallDir 'zed-listener.log'

function Write-Step { param([string]$Message) Write-Host "==> $Message" -ForegroundColor Cyan }
function Write-Detail { param([string]$Message) Write-Host "    $Message" }

function Resolve-PwshExe {
    $here = Join-Path $PSHOME 'pwsh.exe'
    if (Test-Path -LiteralPath $here -PathType Leaf) { return $here }

    $onPath = Get-Command -Name 'pwsh' -CommandType Application -ErrorAction SilentlyContinue |
        Select-Object -First 1
    if ($onPath) { return $onPath.Source }

    $default = Join-Path $env:ProgramFiles 'PowerShell\7\pwsh.exe'
    if (Test-Path -LiteralPath $default -PathType Leaf) { return $default }

    throw 'PowerShell 7 (pwsh.exe) is required but was not found'
}

function Get-ListenerProcess {
    @(
        Get-CimInstance Win32_Process -Filter "Name='pwsh.exe' OR Name='wscript.exe' OR Name='cmd.exe'" -ErrorAction SilentlyContinue |
            Where-Object {
                $_.CommandLine -and
                $_.CommandLine -match [regex]::Escape($ProcessMatch) -and
                $_.ProcessId -ne $PID
            }
    )
}

# Retries because the watchdog trigger can start a fresh instance while we are
# killing the previous one; a single pass can leave an orphan holding the port.
function Stop-Listener {
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    }

    for ($attempt = 0; $attempt -lt 5; $attempt++) {
        # PowerShell unrolls a one-element array on return, so re-wrap it here.
        $stale = @(Get-ListenerProcess)
        if ($stale.Count -eq 0) { break }
        foreach ($proc in $stale) {
            try {
                Stop-Process -Id $proc.ProcessId -Force -ErrorAction Stop
                Write-Detail "stopped old $($proc.Name) (pid $($proc.ProcessId))"
            }
            catch { }
        }
        Start-Sleep -Milliseconds 500
    }
}

function Write-HiddenVbs {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Exe,
        [Parameter(Mandatory)][string]$ArgLine
    )
    # Output goes to NUL, not to the log, and the listener opens the log itself.
    # A `>> file` redirect here would give cmd an inheritable handle to that file,
    # which Zed and the ssh.exe it spawns inherit and hold for the whole remote
    # session -- after which no restart could reopen it. NUL cannot be pinned.
    # cmd /c idiom for a spaced exe path plus redirection: cmd /c ""exe" args > NUL 2>&1"
    $cmd = 'cmd /c "' + '"' + $Exe + '" ' + $ArgLine + ' > NUL 2>&1' + '"'
    $literal = $cmd.Replace('"', '""')   # VBS escapes a quote by doubling it
    $content = @"
' Generated by install-zed-listener.ps1. Runs the command hidden (style 0).
Set shell = CreateObject("WScript.Shell")
shell.Run "$literal", 0, True
"@
    Set-Content -LiteralPath $Path -Value $content -Encoding ASCII
    Write-Detail "wrote $Path"
}

function Register-ListenerTask {
    $me = "$env:USERDOMAIN\$env:USERNAME"
    $action = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument ('"{0}"' -f $VbsPath)
    $atLogon = New-ScheduledTaskTrigger -AtLogOn -User $me
    # Watchdog: fires every minute and is skipped by IgnoreNew while the listener
    # is alive, so it only has an effect once the listener has actually died.
    $watchdog = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Minutes 1)
    $principal = New-ScheduledTaskPrincipal -UserId $me -LogonType Interactive -RunLevel Limited
    $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
        -ExecutionTimeLimit ([TimeSpan]::Zero) -MultipleInstances IgnoreNew -StartWhenAvailable -Hidden

    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger @($atLogon, $watchdog) `
        -Principal $principal -Settings $settings -Force | Out-Null
    Write-Detail "registered task '$TaskName'"
}

function Wait-ForListening {
    param([int]$TimeoutSeconds = 30)
    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    while ((Get-Date) -lt $deadline) {
        $listening = Get-NetTCPConnection -State Listen -LocalPort $Port -ErrorAction SilentlyContinue |
            Where-Object { $_.LocalAddress -eq '127.0.0.1' }
        if ($listening) { return $true }
        Start-Sleep -Milliseconds 500
    }
    return $false
}

if ($Uninstall) {
    Write-Step "uninstalling '$TaskName'"

    # Unregister before killing anything. Stopping first leaves a window in which
    # the one-minute watchdog can start a replacement that then outlives the task.
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Detail "unregistered task '$TaskName'"
    }
    else {
        Write-Detail "no task '$TaskName' registered"
    }

    Stop-Listener

    if (Test-Path -LiteralPath $InstallDir) {
        try {
            Remove-Item -LiteralPath $InstallDir -Recurse -Force -ErrorAction Stop
            Write-Detail "removed $InstallDir (including the log)"
        }
        catch {
            # An old install could leave the log pinned by a Zed session. The task
            # is already gone, so report it rather than failing the uninstall.
            Write-Warning "could not fully remove $InstallDir -- $($_.Exception.Message)"
            Write-Detail 'the task is unregistered; delete the folder once Zed is closed'
        }
    }

    Write-Host ''
    Write-Host 'Uninstalled.' -ForegroundColor Green
    return
}

Write-Step 'resolving dependencies'
$zedPath = Resolve-ZedCliPath -Explicit $ZedExe
Write-Detail "zed cli : $zedPath"
$pwshPath = Resolve-PwshExe
Write-Detail "pwsh    : $pwshPath"

$source = Join-Path $PSScriptRoot $ListenerName
if (-not (Test-Path -LiteralPath $source -PathType Leaf)) {
    throw "listener script not found next to the installer: $source"
}

Write-Step 'stopping any running instance'
Stop-Listener

Write-Step "installing to $InstallDir"
New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
Copy-Item -LiteralPath $source -Destination $ScriptPath -Force
Write-Detail "copied $ListenerName"

$argLine = '-NoLogo -NoProfile -File "{0}" -Port {1} -ZedExe "{2}" -LogFile "{3}"' -f $ScriptPath, $Port, $zedPath, $LogFile
Write-HiddenVbs -Path $VbsPath -Exe $pwshPath -ArgLine $argLine

Write-Step 'registering Scheduled Task'
Register-ListenerTask

if ($NoStart) {
    Write-Host ''
    Write-Host 'Installed (not started; -NoStart was given).' -ForegroundColor Green
    return
}

Write-Step 'starting'
Start-ScheduledTask -TaskName $TaskName
if (Wait-ForListening) {
    Write-Detail "listening on 127.0.0.1:$Port"
}
else {
    Write-Warning "not listening on 127.0.0.1:$Port yet -- check $LogFile"
}

Write-Host ''
Write-Host 'Installed.' -ForegroundColor Green
Write-Host "  task : $TaskName"
Write-Host "  dir  : $InstallDir"
Write-Host "  log  : $LogFile"
Write-Host "  port : 127.0.0.1:$Port"
